#!/bin/env python
# -*- coding: utf-8 -*-

# Custom count tool
# caofx@youdao: 2009-06-13 22:22:14

import sys

last = None
n = 0

for line in sys.stdin:
    line = line[0:-1]
    if line != last:
        if last != None: print last, n
        last = line
        n = 0
    n += 1

if last != None: print last, n
